// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
// Copyright 2022, John McNamara, jmcnamara@cpan.org

use rust_xlsxwriter::{Workbook, XlsxError};

mod common;

// Test to demonstrate autofit.
fn create_new_xlsx_file_1(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    let worksheet = workbook.add_worksheet();

    worksheet.write_string_only(0, 0, "A")?;
    worksheet.write_string_only(0, 1, "A")?;

    worksheet.autofit();

    worksheet.set_column_width(1, 1.57)?;

    workbook.save(filename)?;

    Ok(())
}

// Test implicit version autofit width.
fn create_new_xlsx_file_2(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    let worksheet = workbook.add_worksheet();

    worksheet.write_string_only(0, 0, "A")?;
    worksheet.write_string_only(0, 1, "A")?;

    worksheet.set_column_width(1, 1.57143)?;

    worksheet.autofit();
    worksheet.autofit();

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn test_autofit03_1() {
    let test_runner = common::TestRunner::new()
        .set_name("autofit03")
        .set_function(create_new_xlsx_file_1)
        .unique("1")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
fn test_autofit03_2() {
    let test_runner = common::TestRunner::new()
        .set_name("autofit03")
        .set_function(create_new_xlsx_file_2)
        .unique("2")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
