// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0 Copyright 2022, John McNamara,
// jmcnamara@cpan.org

use rust_xlsxwriter::{Format, Workbook, XlsxError};

mod common;

// Test case to demonstrate creating a basic file with some string cell data.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new(filename);

    let format1 = Format::new()
        .set_num_format_index(2)
        .register_with(&mut workbook);

    let format2 = Format::new()
        .set_num_format_index(10)
        .register_with(&mut workbook);

    let format3 = Format::new()
        .set_num_format_index(49)
        .register_with(&mut workbook);

    let worksheet = workbook.add_worksheet();
    worksheet.write_number(0, 0, 1, &format1)?;
    worksheet.write_number(1, 1, 2, &format2)?;
    worksheet.write_number(2, 2, 3, &format3)?;

    workbook.close()?;

    Ok(())
}

#[test]
fn bootstrap14_number_format_via_legacy_index() {
    let testcase = "bootstrap15";

    let (excel_file, xlsxwriter_file) = common::get_xlsx_filenames(testcase);
    _ = create_new_xlsx_file(&xlsxwriter_file);
    common::assert_eq(&excel_file, &xlsxwriter_file);
    common::remove_test_xlsx_file(&xlsxwriter_file);
}
