// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0 Copyright 2022, John McNamara,
// jmcnamara@cpan.org

use rust_xlsxwriter::{Workbook, XlsxError};

mod common;

// Test case to demonstrate creating a basic file with 1 worksheet and no data.
fn create_new_xlsx_file_1(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new(filename);
    _ = workbook.add_worksheet();

    workbook.close()?;

    Ok(())
}

// Test case to demonstrate creating a basic file with 1 worksheet and no data.
// Has an implicit add_worksheet.
fn create_new_xlsx_file_2(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new(filename);

    workbook.close()?;

    Ok(())
}

#[test]
fn bootstrap01_single_worksheet() {
    let test_runner = common::TestRunner::new("bootstrap01")
        .unique("1")
        .initialize();

    _ = create_new_xlsx_file_1(test_runner.output_file());

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
fn bootstrap01_add_default_worksheet() {
    let test_runner = common::TestRunner::new("bootstrap01")
        .unique("2")
        .initialize();

    _ = create_new_xlsx_file_2(test_runner.output_file());

    test_runner.assert_eq();
    test_runner.cleanup();
}
