// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0 Copyright 2022, John McNamara,
// jmcnamara@cpan.org

use rust_xlsxwriter::{Workbook, XlsxError};

mod common;

// Test case to demonstrate creating a basic file with 3 worksheets and no data.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new(filename);
    _ = workbook.add_worksheet().set_name("Foo");
    _ = workbook.add_worksheet();
    _ = workbook.add_worksheet().set_name("Bar");

    workbook.close()?;

    Ok(())
}

#[test]
fn bootstrap03_multiple_worksheets_with_names() {
    let test_runner = common::TestRunner::new("bootstrap03").initialize();

    _ = create_new_xlsx_file(test_runner.output_file());

    test_runner.assert_eq();
    test_runner.cleanup();
}
