// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0 Copyright 2022, John McNamara,
// jmcnamara@cpan.org

use rust_xlsxwriter::{Workbook, XlsxError};

mod common;

// Test case to demonstrate creating a basic file with some numeric cell data.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();

    worksheet.write_number_only(0, 0, 1 as u32)?;
    worksheet.write_number_only(1, 1, 2 as f32)?;
    worksheet.write_number_only(2, 2, 3)?;

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn bootstrap04_write_numbers() {
    let test_runner = common::TestRunner::new("bootstrap04").initialize();

    let result = create_new_xlsx_file(test_runner.output_file());
    assert_result!(result);

    test_runner.assert_eq();
    test_runner.cleanup();
}
