// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0 Copyright 2022, John McNamara,
// jmcnamara@cpan.org

use rust_xlsxwriter::{Workbook, XlsxError};

mod common;

// Test case to demonstrate setting headers and footers.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new(filename);

    let worksheet = workbook.add_worksheet();

    worksheet.set_header("&CPage &P of &N");
    worksheet.set_footer("&R&F");

    worksheet.set_portrait();

    let worksheet = workbook.add_worksheet();

    worksheet.set_header("&C&[Page]&[Pages]&[Date]&[Time]&[Path]&[File]&[File]&[Tab]");

    worksheet.set_portrait();

    workbook.close()?;

    Ok(())
}

#[test]
fn bootstrap40_header_footer() {
    let test_runner = common::TestRunner::new("bootstrap41")
        .ignore_calc_chain()
        .initialize();

    _ = create_new_xlsx_file(test_runner.output_file());

    test_runner.assert_eq();
    test_runner.cleanup();
}
