// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0 Copyright 2022, John McNamara,
// jmcnamara@cpan.org

use rust_xlsxwriter::{Format, Workbook, XlsxAlign, XlsxError};

mod common;

// Test case to demonstrate creating a basic file with alignment formatting.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new(filename);
    let worksheet = workbook.add_worksheet();
    let format1 = Format::new().set_align(XlsxAlign::Left);
    let format2 = Format::new().set_align(XlsxAlign::Center);
    let format3 = Format::new().set_align(XlsxAlign::Right);
    let format4 = Format::new().set_align(XlsxAlign::Fill);
    let format5 = Format::new().set_align(XlsxAlign::Justify);
    let format6 = Format::new().set_align(XlsxAlign::CenterAcross);
    let format7 = Format::new().set_align(XlsxAlign::Distributed);
    let format8 = Format::new().set_align(XlsxAlign::Bottom);
    let format9 = Format::new().set_align(XlsxAlign::VerticalCenter);
    let format10 = Format::new().set_align(XlsxAlign::Top);
    let format11 = Format::new().set_align(XlsxAlign::VerticalJustify);
    let format12 = Format::new().set_align(XlsxAlign::VerticalDistributed);
    let format13 = Format::new()
        .set_align(XlsxAlign::Center)
        .set_align(XlsxAlign::VerticalCenter);

    worksheet.write_string_only(0, 0, "Rust")?;
    worksheet.write_string(1, 0, "Rust", &format1)?;
    worksheet.write_string(2, 0, "Rust", &format2)?;
    worksheet.write_string(3, 0, "Rust", &format3)?;
    worksheet.write_string(4, 0, "Rust", &format4)?;
    worksheet.write_string(5, 0, "Rust", &format5)?;
    worksheet.write_string(6, 0, "Rust", &format6)?;
    worksheet.write_string(7, 0, "Rust", &format7)?;
    worksheet.write_string(8, 0, "Rust", &format8)?;
    worksheet.write_string(9, 0, "Rust", &format9)?;
    worksheet.write_string(10, 0, "Rust", &format10)?;
    worksheet.write_string(11, 0, "Rust", &format11)?;
    worksheet.write_string(12, 0, "Rust", &format12)?;
    worksheet.write_string(13, 0, "Rust", &format13)?;

    workbook.close()?;

    Ok(())
}

#[test]
fn bootstrap29_alignment() {
    let test_runner = common::TestRunner::new("bootstrap29").initialize();

    _ = create_new_xlsx_file(test_runner.output_file());

    test_runner.assert_eq();
    test_runner.cleanup();
}
