// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2023, John McNamara, jmcnamara@cpan.org

use rust_xlsxwriter::{Format, Workbook, XlsxError};

mod common;

// Test case to demonstrate creating a basic file with some string cell data.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();

    let format1 = Format::new().set_bold();

    worksheet.write_formula(0, 0, "=1+2+3-6")?;
    worksheet.write_formula(1, 0, "=SIN(0)")?;
    worksheet.write_formula_with_format(2, 0, "SIN(0)", &format1)?; // No equals sign.
    worksheet
        .write_formula(3, 0, "=1+1")?
        .set_formula_result(3, 0, "2");
    worksheet
        .write_formula_with_format(4, 0, "1+1", &format1)?
        .set_formula_result(4, 0, "2");

    let worksheet = workbook.add_worksheet();
    worksheet.set_formula_result_default("2");
    worksheet.write_formula(0, 0, "=2")?;
    worksheet.write_formula(1, 0, "=1+1")?;

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn bootstrap35_write_formula_with_format() {
    let test_runner = common::TestRunner::new()
        .set_name("bootstrap35")
        .set_function(create_new_xlsx_file)
        .ignore_calc_chain()
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
