name: 🐞 Bug

description: File a bug/issue in rust_xlsxwriter

title: "Bug: <add a description here>"

labels: [bug]

body:

- type: markdown
  attributes:
    value: Please fill in the title above and the sections below to submit your bug report.

- type: textarea
  attributes:
    label: Current behavior
    description: A description of what you're experiencing.
  validations:
    required: true

- type: textarea
  attributes:
    label: Expected behavior
    description: A description of what you expected to happen.
  validations:
    required: true

- type: textarea
  attributes:
    label: Sample code to reproduce
    description: Please add a small, complete, sample program that demonstrates your issue.
    value: |
        ```rust
        use rust_xlsxwriter::{Workbook, XlsxError};

        fn main() -> Result<(), XlsxError> {
            let mut workbook = Workbook::new();
            let worksheet = workbook.add_worksheet();

            worksheet.write_string(0, 0, "Hello")?;

            workbook.save("test.xlsx")?;
            Ok(())
        }
        ```
    render: markdown
  validations:
    required: true

- type: textarea
  attributes:
    label: Environment
    description: |
      Any relevant version or system information:
    value: |
        - rust_xlsxwriter version:
        - rustc version:
        - Excel version:
        - OS:
    render: markdown
  validations:
    required: false


- type: textarea
  attributes:
    label: Any other information
    description: |
      Anything that will give more context about the issue you are encountering.

      Tip: You can attach images by clicking this area to highlight it and then dragging files in.
  validations:
    required: false


- type: markdown
  attributes:
    value: |
      **Note** for OpenOffice and LibreOffice users: Please verify that the
      issue being reported also happens in Excel.

