// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2024, John McNamara, jmcnamara@cpan.org

use crate::common;
use rust_xlsxwriter::{Button, Workbook, XlsxError};

// Create rust_xlsxwriter file to compare against Excel file.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    workbook.add_vba_project("tests/input/macros/vbaProject02.bin")?;

    let worksheet = workbook.add_worksheet();

    let button = Button::new().set_macro("say_hello").set_caption("Hello");
    worksheet.insert_button(1, 2, &button)?;

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn test_button07() {
    let test_runner = common::TestRunner::new()
        .set_name("button07")
        .has_macros()
        .set_function(create_new_xlsx_file)
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
