// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2025, John McNamara, jmcnamara@cpan.org

use crate::common;
use rust_xlsxwriter::{
    chart::ChartSolidFill, Chart, ChartDataLabel, ChartDataLabelPosition, ChartFont, ChartFormat,
    ChartLine, ChartType, Workbook, XlsxError,
};

// Create a rust_xlsxwriter file to compare against an Excel file.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    let worksheet = workbook.add_worksheet();
    // Add some test data for the chart(s).
    let data = [[1, 2, 3], [2, 4, 6], [3, 6, 9], [4, 8, 12], [5, 10, 15]];
    for (row_num, row_data) in data.iter().enumerate() {
        for (col_num, col_data) in row_data.iter().enumerate() {
            worksheet.write_number(row_num as u32, col_num as u16, *col_data)?;
        }
    }

    let data_labels = vec![ChartDataLabel::new()
        .show_value()
        .set_position(ChartDataLabelPosition::Center)
        .set_font(
            ChartFont::new()
                .set_color("#FF0000")
                .set_bold()
                .set_italic(),
        )
        .set_format(
            ChartFormat::new()
                .set_border(ChartLine::new().set_color("#FF0000"))
                .set_solid_fill(ChartSolidFill::new().set_color("#00B050")),
        )
        .to_custom()];

    let mut chart = Chart::new(ChartType::Column);
    chart.set_axis_ids(102521856, 98308480);

    chart
        .add_series()
        .set_values(("Sheet1", 0, 0, 4, 0))
        .set_custom_data_labels(&data_labels);

    chart.add_series().set_values(("Sheet1", 0, 1, 4, 1));
    chart.add_series().set_values(("Sheet1", 0, 2, 4, 2));

    worksheet.insert_chart(8, 4, &chart)?;

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn test_chart_data_labels54() {
    let test_runner = common::TestRunner::new()
        .set_name("chart_data_labels54")
        .set_function(create_new_xlsx_file)
        .ignore_elements("xl/charts/chart1.xml", "<c:layout/>")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
