// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2025, John McNamara, jmcnamara@cpan.org

use crate::common;
use rust_xlsxwriter::{Color, Format, Workbook, XlsxError};

// Create rust_xlsxwriter file to compare against Excel file.
fn create_new_xlsx_file_1(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();

    let format = Format::new().set_background_color(Color::Red);

    worksheet.insert_checkbox_with_format(8, 4, false, &format)?;

    workbook.save(filename)?;

    Ok(())
}

// Test with standard boolean value and format.
fn create_new_xlsx_file_2(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();
    let worksheet = workbook.add_worksheet();
    let format = Format::new()
        .set_checkbox()
        .set_background_color(Color::Red);

    worksheet.write_boolean_with_format(8, 4, false, &format)?;

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn test_checkbox04_1() {
    let test_runner = common::TestRunner::new()
        .set_name("checkbox04")
        .set_function(create_new_xlsx_file_1)
        .unique("1")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
fn test_checkbox04_2() {
    let test_runner = common::TestRunner::new()
        .set_name("checkbox04")
        .set_function(create_new_xlsx_file_2)
        .unique("2")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
