// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2025, John McNamara, jmcnamara@cpan.org

use crate::common;
use rust_xlsxwriter::{FontScheme, Format, Workbook, XlsxError};

// Create a rust_xlsxwriter file to compare against an Excel file.
fn create_new_xlsx_file_1(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    let calibri_body = Format::default();
    let calibri_normal = Format::new()
        .set_font_name("Calibri")
        .set_font_size(11)
        .set_font_scheme(FontScheme::None);

    let worksheet = workbook.add_worksheet();

    worksheet.write_string_with_format(0, 0, "Hello", &calibri_body)?;
    worksheet.write_string_with_format(1, 0, "Hello", &calibri_normal)?;

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn test_default_format16() {
    let test_runner = common::TestRunner::new()
        .set_name("default_format16")
        .set_function(create_new_xlsx_file_1)
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
