// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2024, John McNamara, jmcnamara@cpan.org

use crate::common;
use rust_xlsxwriter::{Image, Workbook, XlsxError};

// Test to demonstrate adding images to worksheets.
fn create_new_xlsx_file(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    let worksheet1 = workbook.add_worksheet();

    let image = Image::new("tests/input/images/red.png")?.set_alt_text("red.png");
    worksheet1.insert_image(8, 4, &image)?;

    let worksheet2 = workbook.add_worksheet();

    let image = Image::new("tests/input/images/yellow.png")?.set_alt_text("yellow.png");
    worksheet2.insert_image(8, 4, &image)?;

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn test_image07() {
    let test_runner = common::TestRunner::new()
        .set_name("image07")
        .set_function(create_new_xlsx_file)
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
