// Test case that compares a file generated by rust_xlsxwriter with a file
// created by Excel.
//
// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Copyright 2022-2025, John McNamara, jmcnamara@cpan.org

use crate::common;
use rust_xlsxwriter::{Image, Workbook, XlsxError};

// Test to demonstrate adding image centering (manually).
fn create_new_xlsx_file_1(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    let worksheet = workbook.add_worksheet();

    worksheet.set_column_width_pixels(0, 32)?;
    worksheet.set_row_height_pixels(4, 96)?;

    let image = Image::new("tests/input/images/red.png")?.set_alt_text("red.png");

    worksheet.insert_image_with_offset(4, 0, &image, 0, 32)?;

    workbook.save(filename)?;

    Ok(())
}

// Test to demonstrate adding image centering (automatic).
fn create_new_xlsx_file_2(filename: &str) -> Result<(), XlsxError> {
    let mut workbook = Workbook::new();

    let worksheet = workbook.add_worksheet();

    worksheet.set_column_width_pixels(0, 32)?;
    worksheet.set_row_height_pixels(4, 96)?;

    let image = Image::new("tests/input/images/red.png")?.set_alt_text("red.png");

    worksheet.insert_image_fit_to_cell_centered(4, 0, &image)?;

    workbook.save(filename)?;

    Ok(())
}

#[test]
fn test_image_scale03_1() {
    let test_runner = common::TestRunner::new()
        .set_name("image_scale03")
        .set_function(create_new_xlsx_file_1)
        .unique("1")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}

#[test]
fn test_image_scale03_2() {
    let test_runner = common::TestRunner::new()
        .set_name("image_scale03")
        .set_function(create_new_xlsx_file_2)
        .unique("2")
        .initialize();

    test_runner.assert_eq();
    test_runner.cleanup();
}
